### ISSUE TITLE
what happened to the nuget package  ?

### ISSUE THREAD

**Issue by kcheick** [sergey-tihon/SwaggerProvider#1]
The nuget package is not available. Is the project still being maintained ?

**Comment by sergey-tihon** [comment]
This one is not ready yet :disappointed: 
It is prototype with type inference, the communication with service is not implemented

**Comment by sergey-tihon** [comment]
I think that something will be published after merge of https://github.com/sergey-tihon/SwaggerProvider/pull/2

**Comment by sergey-tihon** [comment]
Current version released as [v0.0.2-alpha](https://www.nuget.org/packages/SwaggerProvider/0.0.2-alpha)
