### ISSUE TITLE
Enable "host" property to be overridden at runtime 

### ISSUE THREAD

**Issue by lawrencetaylor** [sergey-tihon/SwaggerProvider#15]
It could well be that there is a way to achieve what I am after - if so please enlighten me!

I wish to use SwaggerProvider to generate clients for my service that are consistent with my documentation as part of my build process to run integration tests.  This involves running integration tests against a "Test" environment before the service is promoted to another environment.

I wish to reuse a single swagger.json file for the documentation for all my environments in my pipeline, but I wish to point my client at different hosts for testing.  Is there currently any way to do this?

**Comment by sergey-tihon** [comment]
These is no way to do it right know... but I think that it is nice to have feature.
It should be not hard to add

**Comment by sergey-tihon** [comment]
Released in [v0.3.5](https://www.nuget.org/packages/SwaggerProvider/0.3.5)

**Comment by lawrencetaylor** [comment]
Thank you - looking forward to trying this out.
